typedef enum {
    TOKEN_EOF=0,
    TOKEN_EOL=1,
    TOKEN_UNCOMPLETED_MULTI_LINE_COMMENT=2,
    // operators start here
    TOKEN_ADD,
    TOKEN_SUB,
    TOKEN_MULT,
    TOKEN_DIVIDE,
    TOKEN_MOD,
    TOKEN_EQUALS,
    TOKEN_IF_EQUALS,
    TOKEN_IF_GREATER_OR_EQUALS,
    TOKEN_IF_GREATER, 
    TOKEN_IF_LESSER_OR_EQUALS,
    TOKEN_IF_LESSER,
    TOKEN_LOGICAL_AND,
    TOKEN_LOGICAL_OR,
    // keywords start here
    TOKEN_KEYWORD_INT,
    TOKEN_KEYWORD_LONG,
    TOKEN_KEYWORD_FLOAT,
    TOKEN_KEYWORD_DOUBLE,
    TOKEN_KEYWORD_SHORT,
    TOKEN_KEYWORD_BOOL,
    TOKEN_KEYWORD_FOR,
    TOKEN_KEYWORD_IF,
    TOKEN_KEYWORD_ELSE,
    TOKEN_KEYWORD_RETURN,
    TOKEN_KEYWORD_BREAK,
    TOKEN_KEYWORD_DO,
    TOKEN_KEYWORD_WHILE,
    TOKEN_KEYWORD_TRUE,
    TOKEN_KEYWORD_FALSE,
    // identifiers here
    TOKEN_IDENT,
    // string literals here
    TOKEN_STRING,
    // number definition
    TOKEN_NUMBER
} token_t;

